/*CREATE A LIBRARY*/
LIBNAME L "C:\OT";
RUN;
/*IMPORT EXCEL*/
PROC IMPORT OUT= B79.EX 
DATAFILE= "C:\OT\SAS Data- DAY 1\TESTCASA.xls" 
DBMS=EXCEL REPLACE;
     SHEET="Sheet1$"; 
     GETNAMES=YES;
     MIXED=YES;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;
PROC IMPORT OUT= B79.GS
DATAFILE= "C:\OT\FINAL GRAND CHART.xls" 
DBMS=EXCEL REPLACE;
     SHEET="RRR$"; 
     GETNAMES=YES;
     MIXED=YES;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;
/*IMPORT TEXT*/
PROC IMPORT OUT= B79.TX 
DATAFILE= "C:\OT\SAS Data- DAY 1\TESTCASA123.txt" 
            DBMS=DLM REPLACE;
     DELIMITER='09'x; 
     GETNAMES=YES;
     DATAROW=2; 
RUN;
/*IMPORT CSV*/
PROC IMPORT OUT= B79.CS 
DATAFILE= "C:\OT\SAS Data- DAY 1\TESTCASA.CSV" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;
