/*YEAR COLUMN*/
DATA B79.A;SET SASHELP.AIR;Y=YEAR(DATE);RUN;
/*AGGREGATION*/
PROC SUMMARY DATA = B79.A MEAN NWAY MISSING;
VAR AIR;CLASS Y;OUTPUT OUT = B79.Y MEAN(AIR) = AVG_AIR;
RUN;
/*MERGING AND TAG CREATION*/
PROC SORT DATA = B79.A;BY Y;RUN;
PROC SORT DATA = B79.Y;BY Y;RUN;
DATA B79.H(DROP =_TYPE_ _FREQ_);MERGE B79.A B79.Y;
BY Y;FORMAT TAG $6.;FORMAT AVG_AIR 10.2;
IF AIR >= AVG_AIR THEN TAG = "HIGH";ELSE TAG = "LOW";
RUN;
/*SQL IN SAS, MACRO ARRAY*/
