PROC SQL;
CREATE TABLE DATANAME AS SELECT * FROM SOURCE DATA
WHERE CONDITIONS;QUIT;
PROC SQL;CREATE TABLE B79.C AS SELECT * 
FROM SASHELP.CLASS;QUIT;
PROC SQL;CREATE TABLE B79.C AS SELECT NAME,AGE,SEX 
FROM SASHELP.CLASS;QUIT;
DATA B79.A;SET SASHELP.CLASS;KEEP NAME AGE SEX;RUN;
PROC SQL;CREATE TABLE B79.C AS SELECT NAME,AGE,SEX 
FROM SASHELP.CLASS WHERE SEX = "F";QUIT;
DATA B79.A;SET SASHELP.CLASS;KEEP NAME AGE SEX;
IF SEX = "F";RUN;
/*GROUPING*/
PROC SUMMARY DATA = SASHELP.CLASS NWAY MISSING MEAN;
VAR AGE HEIGHT WEIGHT;CLASS SEX;
OUTPUT OUT = B79.H MEAN(AGE) = AVG_AGE
MEAN(HEIGHT) = AVG_HT MEAN(WEIGHT) = AVG_WT;RUN;
PROC SQL;CREATE TABLE B79.Y AS SELECT
SEX,COUNT(NAME) AS FREQ,MEAN(AGE) AS AVG_AGE,
MEAN(HEIGHT) AS AVG_HT, MEAN(WEIGHT) AS AVG_WT
FROM SASHELP.CLASS GROUP BY SEX;QUIT;
/*DISTINCT COUNT*/
PROC SQL;CREATE TABLE B79.H AS SELECT 
COUNT(DISTINCT(AGE)) AS CN FROM SASHELP.CLASS;QUIT;
PROC SQL;CREATE TABLE B79.H AS SELECT 
SEX,COUNT(DISTINCT(AGE)) AS CN 
FROM SASHELP.CLASS GROUP BY SEX;QUIT;
/*MERGING*/
DATA B79.A;SET SASHELP.AIR;M=MONTH(DATE);RUN;
DATA B79.C;SET SASHELP.CLASS;L=_N_;RUN;
PROC SQL;CREATE TABLE B79.H AS SELECT * FROM
B79.A X,B79.C Y WHERE X.M=Y.L;QUIT;
PROC SQL;CREATE TABLE B79.H AS SELECT X.*,Y.NAME,Y.AGE
FROM B79.A X,B79.C Y WHERE X.M=Y.L;QUIT;
/*SORTING*/
PROC SQL;CREATE TABLE B79.H AS SELECT X.*,Y.NAME,Y.AGE
FROM B79.A X,B79.C Y WHERE X.M=Y.L ORDER BY NAME;QUIT;
/*YEAR COLUMN*/
DATA B79.A;SET SASHELP.AIR;Y=YEAR(DATE);RUN;
/*AGGREGATION*/
PROC SQL;CREATE TABLE B79.H
AS SELECT *,MEAN(AIR) AS AVG_AIR FROM B79.A GROUP BY Y;
QUIT;
/*TAG CREATION*/
DATA B79.H;SET B79.H;
BY Y;FORMAT TAG $6.;FORMAT AVG_AIR 10.2;
IF AIR >= AVG_AIR THEN TAG = "HIGH";ELSE TAG = "LOW";
RUN;
