/*DATA CHANGES*/
DATA NEWLIBNAME.NEWDATA;
SET OLDLIBNAME.OLDDATA;
NEW VAR = FUNC(OLD VAR);
FORMAT VAR1 VAR2 W.D;
RUN;
/*NUMERIC FUNCTIONS*/
DATA B79.C;SET SASHELP.CLASS;
X=LOG(AGE);Y=LOG(HEIGHT);
X10 = LOG10(AGE);Z = EXP(AGE);
SQ_WT = WEIGHT**2;SQT_WT = WEIGHT**0.5;
CB_WT = WEIGHT**3;INV = 1/AGE;
A= ABS(WEIGHT);
R = ROUND(WEIGHT);
I=INT(WEIGHT);
S=SUM(AGE,WEIGHT,HEIGHT);
M=MEAN(AGE,WEIGHT,HEIGHT);
ST=STD(AGE,WEIGHT,HEIGHT);
V=VAR(AGE,WEIGHT,HEIGHT);
M=MIN(AGE,WEIGHT,HEIGHT);
M=MAX(AGE,WEIGHT,HEIGHT);
N = LOG(S)+M/10-V*5+WEIGHT**2/100;
FORMAT X Y X10 SQT_WT 10.2;
FORMAT V N 10.;
RUN;
/*STRING FUNCTIONS*/
DATA B79.C1;SET SASHELP.CLASS;
D = LENGTH(NAME);J = SEX||NAME;J1 = SEX||" "||NAME;
J2 = SEX||"@1234@"||NAME;Y = SEX||AGE;
Y1 = COMPRESS(SEX||AGE);Y2 = SEX||STRIP(AGE);
Y3 = COMPBL(SEX||AGE);Y4 = SEX||" "||STRIP(AGE);
C=COMPRESS(J2,"@2Aa");
/*S=SUBSTR(STRING,START POINT,NO OF CHAR);*/
S= SUBSTR(NAME,1,4);S1= SUBSTR(NAME,3,3);
U = UPCASE(NAME);B=LOWCASE(NAME);
I = INDEX(UPCASE(NAME),"A");
Z=SCAN(J2,1,"@");Z1=SCAN(J2,2,"@");Z2=SCAN(J2,3,"@");
Q=Z1*1;Q1=COMPRESS(STRIP(Q||""));
RUN;
DATA B79.C;SET SASHELP.CLASS;
S=SUBSTR(NAME,1,1)||SUBSTR(NAME,3,1)||SUBSTR(NAME,5,1);
S1= SUBSTR(NAME,LENGTH(NAME)-3,4);RUN;
