/*DATE FUNCTIONS*/
DATA B79.A;SET SASHELP.AIR;S = DATE;
FORMAT S WEEKDATE30.;FORMAT M M1 M2 M3 M4 M5 T DDMMYY10.;
Z=DAY(S);C=MONTH(S);F=YEAR(S);Q=QTR(S);
W=WEEKDAY(S);M = MDY(C,Z,F);M1=M+40;
/*NEWDATE = INTNX("UNIT",START DATE,NO. OF UNITS,OPTION);*/
M2=INTNX("MONTHS",M1,3);M3=INTNX("MONTHS",M1,3,'E');
M4=INTNX("MONTHS",M1,3,'S');M5=INTNX("WEEKS",M1,-6,'S');
T = TODAY();
/*DIFF = INTCK("UNIT",DATE1,DATE2);*/
D1 = INTCK("WEEKS",M1,M4);
D2 = INTCK("DAYS",M1,M4);
V=M4-M1;
RUN;
/*KEEP & DROP*/
DATA B79.C;SET SASHELP.CLASS;KEEP NAME SEX AGE;RUN;
DATA B79.C;SET SASHELP.CLASS;DROP SEX AGE;RUN;
/*EFFICIENT WAY OF KEEP/DROP*/
DATA B79.C1(DROP = SEX AGE);SET SASHELP.CLASS;RUN;
/*RENAME AND LABEL*/
DATA B79.C;SET SASHELP.CLASS;
RENAME SEX = GENDER;
LABEL AGE = "AGE OF THE STUDENTS";RUN;
/*STRUCTURE OF THE DATA*/
PROC CONTENTS DATA = B79.C;RUN;
PROC CONTENTS DATA = SASHELP.CITIDAY;RUN;
/*TITLE & FOOTNOTE*/
TITLE "KOLKATA SAS CLASS";
FOOTNOTE "BATCH 79, IVY";
/*MULTIPLE LINES OF TITLE & FOOTNOTE*/
TITLE1 "KOLKATA SAS CLASS";
TITLE2 "CAMAC STREET";
FOOTNOTE1 "BATCH 79, IVY";
FOOTNOTE2 "SAS LESSON PROC";
PROC CONTENTS DATA = SASHELP.CITIDAY;
TITLE "1ST PROC LESSON";
FOOTNOTE "SUNDAY 29, NOV 2015";RUN;
/*ERASE THE MEMORY*/
TITLE;FOOTNOTE;
/*TRANSFER OUTPUT TO EXTERNAL FILE*/
/*EXCEL*/
ODS HTML FILE = "C:\OT\A.XLS";
PROC CONTENTS DATA = SASHELP.CITIDAY;
TITLE "1ST PROC LESSON";
FOOTNOTE "SUNDAY 29, NOV 2015";RUN;
ODS HTML CLOSE;
/*WORD*/
ODS HTML FILE = "C:\OT\A.DOC";
PROC CONTENTS DATA = SASHELP.CITIDAY;
TITLE "1ST PROC LESSON";
FOOTNOTE "SUNDAY 29, NOV 2015";RUN;
ODS HTML CLOSE;
/*HTML*/
ODS HTML FILE = "C:\OT\A.HTML";
PROC CONTENTS DATA = SASHELP.CITIDAY;
TITLE "1ST PROC LESSON";
FOOTNOTE "SUNDAY 29, NOV 2015";RUN;
ODS HTML CLOSE;
/*PDF*/
ODS PDF FILE = "C:\OT\A.PDF";
PROC CONTENTS DATA = SASHELP.CITIDAY;
TITLE "1ST PROC LESSON";
FOOTNOTE "SUNDAY 29, NOV 2015";RUN;
ODS PDF CLOSE;
