/*PRINT*/
/*ENTIRE DATA*/
PROC PRINT DATA = SASHELP.CLASS;RUN;
/*SOME VARIABLES*/
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;RUN;
/*SOME OBS*/
PROC PRINT DATA = SASHELP.CLASS (OBS = 6);
VAR NAME AGE SEX;RUN;
PROC PRINT DATA = SASHELP.CLASS (FIRSTOBS = 3 OBS = 8);
VAR NAME AGE SEX;RUN;
/*CONDITIONS*/
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;
WHERE SEX = "F";RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;
WHERE AGE<13;RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;
WHERE AGE>14;RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;
WHERE 13<=AGE<=14;RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;
WHERE AGE<13 OR AGE > 14;RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;
WHERE NOT(13<=AGE<=14);RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME AGE SEX;
WHERE SEX = "F" AND NOT(13<=AGE<=14);RUN;
/*PRINT ALL DATES THAT ARE WEEKENDS AFTER 1955*/
PROC PRINT DATA = SASHELP.AIR;VAR DATE;
FORMAT DATE WEEKDATE30.;
WHERE YEAR(DATE) > 1955 AND 
(WEEKDAY(DATE) = 1 OR WEEKDAY(DATE) = 7);RUN;
PROC PRINT DATA = SASHELP.AIR;VAR DATE;
FORMAT DATE WEEKDATE30.;
WHERE YEAR(DATE) > 1955 AND 
WEEKDAY(DATE) IN (1,7);RUN;
PROC PRINT DATA = SASHELP.AIR;VAR DATE;
FORMAT DATE WEEKDATE30.;
WHERE YEAR(DATE) > 1955 AND 
NOT(2<=WEEKDAY(DATE) <=6);RUN;
/*PRINT NAME SEX AGE OF FEMALES WITH NAME STARTING WITH*/
/*J*/
PROC PRINT DATA = SASHELP.CLASS;VAR NAME SEX AGE;
WHERE SEX = "F" AND SUBSTR(NAME,1,1) = "J";RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME SEX AGE;
WHERE SEX = "F" AND INDEX(NAME,"J") = 1;RUN;
PROC PRINT DATA = SASHELP.CLASS;VAR NAME SEX AGE;
WHERE SEX = "F" AND NAME LIKE "J%";RUN;
/*< LT*/
/*> GT*/
/*<= LE*/
/*>= GE*/
/*~ NOT*/
/*= EQ*/
/*<> ~= NE*/
/*IF THEN ELSE DO*/
DATA NEW;
SET OLD;
IF CONDITION THEN ACTION;
ELSE IF CONDITION THEN ACTION;
.....;
ELSE ACTION;RUN;
/*2 CATEGORY*/
DATA B79.C;SET SASHELP.CLASS;FORMAT X 10.2;
IF SEX = "F" THEN X = LOG(AGE);ELSE X = AGE**2;RUN;
/*> 2 CATEGORIES*/
DATA B79.C;SET SASHELP.CLASS;FORMAT TAG $30.;
IF AGE < 13 THEN TAG = "AGE BELOW 13";
ELSE IF AGE <=14 THEN TAG = "AGE BETWEEN 13 AND 14";
ELSE TAG = "AGE ABOVE 14";RUN;
/*MULTIPLE ACTION*/
DATA NEW;
SET OLD;
IF CONDITION THEN DO;
ACTION1;ACTION2;...;ACTION N;END;
ELSE IF CONDITION THEN DO;
ACTION1;ACTION2;...;ACTION N;END;
.....;
ELSE DO;
ACTION1;ACTION2;...;ACTION N;END;RUN;
DATA B79.C;SET SASHELP.CLASS;FORMAT TAG $30.;
FORMAT X Y Z 10.2;
IF AGE < 13 THEN DO;
X = LOG(AGE);Y = LOG(HEIGHT);
Z=LOG(WEIGHT);TAG = "AGE BELOW 13";END;
ELSE IF AGE <=14 THEN DO;
X = 1000;Y=999;Z = 888;
TAG = "AGE BETWEEN 13 AND 14";END;
ELSE DO;X = AGE**2;Y=HEIGHT**2;
Z = WEIGHT**2;TAG = "AGE ABOVE 14";END;RUN;
