DATA B79.A;SET SASHELP.AIR;FORMAT TAG $15.;
FORMAT DATE WEEKDATE30.;
IF QTR(DATE) = 1 THEN FQ = 4;
ELSE FQ = QTR(DATE) - 1;
IF WEEKDAY(DATE) IN (4,5) THEN TAG = "WED/THU";
ELSE IF WEEKDAY(DATE) IN (1,7) THEN TAG = "WEEKENDS";
ELSE TAG = "OTHER WEEKDAYS";
RUN;
DATA B79.C;SET SASHELP.CLASS;
FORMAT TAG $40.;FORMAT X Y Z 10.2; 
IF SEX = "M" AND AGE < 13 THEN DO;
X = LOG(AGE); Y = LOG(HEIGHT); Z = LOG(WEIGHT);
TAG = "MALE WITH AGE < 13";END;
ELSE IF SEX = "F" AND AGE < 13 THEN DO;
X = 4000; Y = 100; Z =999;
TAG = "FEMALE WITH AGE < 13";END;
ELSE IF SEX = "M" AND AGE <= 14 THEN DO;
X = AGE**2; Y = HEIGHT**2; Z = WEIGHT**2;
TAG = "MALE WITH AGE BETWEEN 13 & 14";END;
ELSE IF SEX = "F" AND AGE <= 14 THEN DO;
X = AGE*10; Y = HEIGHT*10; Z = WEIGHT*10;
TAG = "FEMALE WITH AGE BETWEEN 13 & 14";END;
ELSE IF SEX = "M" AND AGE > 14 THEN DO;
X = AGE**0.5; Y = HEIGHT**0.5; Z = WEIGHT**0.5;
TAG = "MALE WITH AGE > 14";END;
ELSE DO; X = AGE*100; Y = HEIGHT*100; Z = WEIGHT*100;
TAG = "FEMALE WITH AGE > 14";END;RUN;
/*SORTING*/
/*CREATE AN OBS NUMBER*/
DATA B79.A;SET SASHELP.CLASS;P=_N_;RUN;
PROC SORT DATA = SASHELP.CLASS OUT = B79.C;
BY SEX;RUN;
/*DESCENDING*/
PROC SORT DATA = SASHELP.CLASS OUT = B79.C;
BY DESCENDING AGE;RUN;
/*MULTIPLE VARIABLES*/
PROC SORT DATA = SASHELP.CLASS OUT = B79.C;
BY SEX DESCENDING AGE;RUN;
/*DUPLICATE REMOVAL*/
/*BASED ON 1 VARIABLE*/
PROC SORT DATA = SASHELP.CLASS NODUPKEY 
OUT = B79.C DUPOUT =B79.C1;BY SEX;RUN;
/*BASED ON >1 VARIABLE*/
PROC SORT DATA = SASHELP.CLASS NODUPKEY 
OUT = B79.C DUPOUT =B79.C1;BY SEX AGE;RUN;
/*BASED ON ALL VARIABLES*/
PROC SORT DATA = SASHELP.CLASS NODUP 
OUT = B79.C DUPOUT =B79.C1;BY SEX;RUN;
DESCRIPTIVE STATS - MEAN,MEDIAN, STANDARD DEV
SKEWNESS, KURTOSIS
CORRELATION
TEST OF HYPOTHESIS - t TEST,
CHI SQUARE TEST (INDEPENDENCE OF ATTRIBUTES)
ANOVA 
/*NODUPKEY WITH ALL VARIABLES*/
