/*DESCRIPTIVE STATS*/
/*DEFAULT STATS ON ALL NUMERIC VARIABLES*/
PROC MEANS DATA = SASHELP.CLASS;RUN;
/*DEFAULT STATS ON SELECTED NUMERIC VARIABLES*/
PROC MEANS DATA = SASHELP.CLASS;VAR AGE WEIGHT;RUN;
/*SELECTED STATS ON ALL NUMERIC VARIABLES*/
PROC MEANS DATA = SASHELP.CLASS MEAN MEDIAN;RUN;
ODS HTML FILE = "C:\OT\A.XLS";
PROC MEANS DATA = SASHELP.CLASS N NMISS 
MEAN MEDIAN VAR STD Q1 Q3 P1 P5 P95 P99 P10 P90
MIN MAX RANGE SUM SKEW KURT CV;RUN;ODS HTML CLOSE;
PROC MEANS DATA = SASHELP.CLASS MEAN MEDIAN;
WHERE SEX = "F";RUN;
/*BY STATEMENT*/
PROC SORT DATA = SASHELP.CLASS OUT = B79.C;BY SEX;RUN;
PROC MEANS DATA =B79.C MEAN MEDIAN;BY SEX;RUN;
PROC PRINT DATA =B79.C;BY SEX;RUN;
/*CLASS STATEMENT*/
PROC MEANS DATA = SASHELP.CLASS MEAN MEDIAN;
CLASS SEX;RUN;
DATA B79.A;SET SASHELP.AIR;
Y = YEAR(DATE);Q=QTR(DATE);RUN;
PROC MEANS DATA = B79.A MEAN;VAR AIR;CLASS Y;RUN;
PROC MEANS DATA = B79.A MEAN;VAR AIR;CLASS Q;RUN;
ODS HTML FILE = "C:\OT\A.XLS";
PROC MEANS DATA = B79.A MEAN;VAR AIR;CLASS Y Q;RUN;
ODS HTML CLOSE;
