/*CREATION OF OUTPUT FILE*/
PROC MEANS DATA = B79.A MEAN NOPRINT;
VAR AIR;CLASS Y Q;
OUTPUT OUT = B79.C MEAN(AIR) = AVG_AIR;RUN;
/*SUMMARY*/
PROC SUMMARY DATA = B79.A MEAN;
VAR AIR;CLASS Y Q;
OUTPUT OUT = B79.C1 MEAN(AIR) = AVG_AIR;RUN;
/*STORING THE FINAL COMBINATION*/
PROC SUMMARY DATA = B79.A MEAN NWAY MISSING;
VAR AIR;CLASS Y Q;
OUTPUT OUT = B79.C1 MEAN(AIR) = AVG_AIR;RUN;
/*UNIVARIATE*/
PROC UNIVARIATE DATA = SASHELP.AIR; VAR AIR;RUN;
/*INCREASED NO OF EXTREME OBSERVATIONS*/
PROC UNIVARIATE DATA = SASHELP.AIR NEXTROBS=20; 
VAR AIR;RUN;
/*TEST FOR NORMALITY*/
PROC UNIVARIATE DATA = SASHELP.AIR NORMAL; 
VAR AIR;HISTOGRAM AIR/NORMAL;RUN;
/*SCATTER PLOT*/
PROC GPLOT DATA = SASHELP.AIR;PLOT AIR*DATE;RUN;
/*ONE SAMPLE t TEST*/
PROC TTEST DATA = SASHELP.CLASS H0=55;VAR HEIGHT;RUN;
/*99% CONF INTERVAL*/
PROC TTEST DATA = SASHELP.CLASS H0=55 ALPHA = 0.01;
VAR HEIGHT;RUN;
/*INDEPENDENT SAMPLE t TEST/UNPAIRED t TEST*/
PROC TTEST DATA = SASHELP.CLASS;VAR HEIGHT;
CLASS SEX;RUN;
