/*ONEWAY ANOVA*/
PROC ANOVA DATA = SASHELP.PRDSAL2;
CLASS COUNTRY;
MODEL ACTUAL = COUNTRY;MEANS COUNTRY;RUN;
PROC ANOVA DATA = SASHELP.PRDSAL2;
CLASS COUNTRY;
MODEL ACTUAL = COUNTRY;MEANS COUNTRY;
WHERE COUNTRY ~= "Mexico";RUN;
/*POST HOC TEST*/
PROC ANOVA DATA = SASHELP.PRDSAL2;
CLASS COUNTRY;
MODEL ACTUAL = COUNTRY;MEANS COUNTRY/TUKEY;RUN;
PROC ANOVA DATA = SASHELP.PRDSAL2;
CLASS COUNTRY;
MODEL ACTUAL = COUNTRY;
MEANS COUNTRY/TUKEY ALPHA = 0.0001;RUN;
/*POST HOC TEST*/
PROC ANOVA DATA = SASHELP.PRDSAL2;
CLASS COUNTRY;
MODEL ACTUAL = COUNTRY;MEANS COUNTRY/SCHEFFE;RUN;
/*N-WAY ANOVA*/
PROC ANOVA DATA = SASHELP.PRDSAL2;
CLASS COUNTRY PRODTYPE;
MODEL ACTUAL = COUNTRY PRODTYPE;
MEANS COUNTRY PRODTYPE;RUN;
/*N-WAY ANOVA AND INTERACTION*/
PROC ANOVA DATA = SASHELP.PRDSAL2;
CLASS COUNTRY PRODTYPE;
MODEL ACTUAL = COUNTRY PRODTYPE COUNTRY*PRODTYPE;
MEANS COUNTRY PRODTYPE COUNTRY*PRODTYPE;RUN;
/*PAIRED t TEST*/
PROC TTEST DATA = SASHELP.PRDSAL2;
PAIRED ACTUAL*PREDICT;RUN;
PROC SORT DATA = SASHELP.PRDSAL2  OUT=B79.S;
BY COUNTRY;RUN;
PROC TTEST DATA = B79.S;
PAIRED ACTUAL*PREDICT;BY COUNTRY;RUN;
/*FREQUENCY*/
/*1 DIMENSIONAL*/
DATA B79.A;SET SASHELP.CLASS;
IF WEIGHT<=90 THEN WG = 1;ELSE WG = 2;RUN;
PROC FREQ DATA = B79.A;TABLES WG SEX;RUN; 
/*2 DIMENSIONAL*/
PROC FREQ DATA = B79.A;TABLES WG*SEX;RUN; 
/*ONLY FREQ*/
PROC FREQ DATA = B79.A;
TABLES WG*SEX/NOPERCENT NOROW NOCOL;RUN; 
/*COL %*/
PROC FREQ DATA = B79.A;
TABLES WG*SEX/NOPERCENT NOROW NOFREQ;RUN; 
/*CHI SQUARE TEST*/
PROC FREQ DATA = B79.A;
TABLES WG*SEX/NOPERCENT NOROW CHISQ;RUN;
/*CORRELATION*/
/*B/W ALL NUMERIC VARIABLES*/
PROC CORR DATA = SASHELP.CLASS;RUN;
/*B/W SELETED VARIABLES*/
PROC CORR DATA = SASHELP.CLASS;VAR AGE HEIGHT;RUN;
/*WITH SELETED VARIABLES*/
PROC CORR DATA = SASHELP.CLASS;VAR AGE HEIGHT;
WITH WEIGHT;RUN;
