/*DISINTEGRATION*/
/*ONLY ONE SUBSET*/
DATA B79.F;SET SASHELP.CLASS;IF SEX = "F";RUN;
DATA B79.F;SET SASHELP.CLASS;IF SEX = "F";
KEEP NAME AGE SEX;RUN;
/*2 SUBSET*/
DATA B79.F B79.M;SET SASHELP.CLASS;
IF SEX = "F" THEN OUTPUT B79.F;ELSE OUTPUT B79.M;
KEEP NAME AGE SEX;RUN;
DATA B79.F(KEEP= NAME AGE SEX) 
B79.M (KEEP = NAME HEIGHT WEIGHT);SET SASHELP.CLASS;
IF SEX = "F" THEN OUTPUT B79.F;ELSE OUTPUT B79.M;RUN;
/*MULTIPLE SUBSET*/
DATA B79.Q1 B79.Q2 B79.Q3 B79.Q4;
SET SASHELP.AIR;
IF QTR(DATE) = 1 THEN OUTPUT B79.Q1;
ELSE IF QTR(DATE) = 2 THEN OUTPUT B79.Q2;
ELSE IF QTR(DATE) = 3 THEN OUTPUT B79.Q3;
ELSE OUTPUT B79.Q4;RUN;
/*APPENDING*/
DATA B79.Y;SET B79.Q1 B79.Q2 B79.Q3 B79.Q4;RUN;
DATA B79.Y;SET B79.Q1 B79.Q2 B79.Q3 B79.Q4;
IF YEAR(DATE) > 1956;RUN;
DATA B79.C;SET B79.F B79.M;RUN;
DATA A B C D E F;SET SASHELP.PRDSAL2;
IF COUNTRY = "U.S.A." AND PRODTYPE = "FURNITURE"
THEN OUTPUT A;
ELSE IF COUNTRY = "U.S.A." AND PRODTYPE = "OFFICE"
THEN OUTPUT B;
ELSE IF COUNTRY = "Mexico" AND PRODTYPE = "FURNITURE"
THEN OUTPUT C;
ELSE IF COUNTRY = "Mexico" AND PRODTYPE = "OFFICE"
THEN OUTPUT D;
ELSE IF COUNTRY = "Canada" AND PRODTYPE = "FURNITURE"
THEN OUTPUT E;
ELSE OUTPUT F;RUN;
