LOGIT MODEL:
Y = 1 OR Y = 0
p = P(Y=1) 
p/(1-p) - ODDS RATIO 
L = ln(p/(1-p)) - LOG OF ODDS
L = A+B1X1+B2X2+...BKXK
p = EXP(L)/(1+EXP(L))
SCORE = 1000*p
FOR VARIABLE X1 - ESTIMATED B1 WILL GIVE
THE IMPACT OF X1 ON L
EXP(B1) WILL CAPTURE IMPACT ON THE ODDS 
RATIO
IF B1>0 i.e. EXP(B1) > 1
THEN INCREASE IN X1 LEADS TO INCREASE IN
RELATIVE PROPENSITY OF THE EVENT Y = 1;
APPLICATION SCORECARD
BEHAVIOURAL SCORECARD
GOOD/BAD DEFINITION - 
OBSERVATION AND PERFORMANCE WINDOW
