LIBNAME L "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\LOGI";
RUN;
/*CLEANED*/
/*GENERATION OF RANDOM SUBSAMPLE*/
DATA D V;
SET L.LOGISTIC;
IF RANUNI(8671) <=0.9 THEN OUTPUT D;
ELSE OUTPUT V;
RUN;
/*PROC REG WITH VIF COLLIN*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\LOGI\L.XLS";
PROC LOGISTIC DATA = D DESCENDING;
MODEL HONCOMP = 
FEMALE 
READ 
MATH 
socst 
SCIENCE
/LACKFIT RSQ;
OUTPUT OUT = L.EST P = PROB;
RUN;
QUIT;
ODS HTML CLOSE;
/*CALLING THE MACRO - ENSURE TO RUN IT BEFORE THIS*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\LOGI\K.XLS";
%KSGCF(L.EST,PROB,HONCOMP,10,KS);
ODS HTML CLOSE;
DATA L.EST;
SET L.EST;
SCORE = ROUND(PROB*1000);
RUN;
/*DIVERGENCE TEST*/
PROC TTEST DATA = L.EST;
VAR SCORE;
CLASS HONCOMP;
RUN;
/*CLUSTERING*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\LOGI\F.XLS";
PROC FREQ DATA = L.EST;
TABLES SCORE;
RUN;
ODS HTML CLOSE;
/*VALIDATION RERUN*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\LOGI\L.XLS";
PROC LOGISTIC DATA = V DESCENDING;
MODEL HONCOMP = FEMALE READ MATH socst SCIENCE;
/*ONLY SIGNIFICANT VARIABLES FROM DEV DATA*/
OUTPUT OUT = L.Y1 P = PROB1;
RUN;
QUIT;
ODS HTML CLOSE;
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\LOGI\K.XLS";
%KSGCF(L.Y1,PROB1,HONCOMP,10,RO);
ODS HTML CLOSE;
/*SCORING*/
DATA L.V1;
SET V;
/*USE SAME ESTIMATED EQUATION FORM DEV MODEL*/
L = A+B1X1+B2X2+...+BKXK;
P = EXP(L)/(1+EXP(L));
RUN;
ODS HTML FILE = "D:\SOUVIK SIR BATCH FILES\BATCH 59\LOGI\K.XLS";
%KSGCF(L.V1,P,HONCOMP,10,RO);
ODS HTML CLOSE;
FINE CLASSING AND COARSE CLASSING
FINE CLASSING - CREATING THE CATEGORIES FOR
CONTINUOUS VARIABLES - CALCULATE WOE AND
INFORMATION VALUE
COARSE CLASSING - LOOK INTO THE WOE PLOT
ACROSS CATEGORIES AND RECATEGORISE BASED ON THE
PLOT TO GET A PROPER GRAPH WHICH SHOULDN'T
HAVE MULTIPLE KINKS
