/*VOLATILITY CHECK*/
DATA B76.A;
SET SASHELP.AIR;
LABEL AIR ="AIR";
RUN;
PROC GPLOT DATA = B76.A;
PLOT AIR*DATE;
RUN;
DATA B76.A;
SET B76.A;
LOG_AIR = LOG(AIR);
SQRT_AIR = AIR**0.5;
RUN;
PROC GPLOT DATA = B76.A;
PLOT SQRT_AIR*DATE;
RUN;
PROC GPLOT DATA = B76.A;
PLOT LOG_AIR*DATE;
RUN;
/*NON STATIONARITY CHECK*/
PROC ARIMA DATA = B76.A;
IDENTIFY VAR = LOG_AIR STATIONARITY = (ADF);
RUN;
DATA B76.A;
SET B76.A;
DIF_LOG_AIR = DIF(LOG_AIR);
RUN;
PROC ARIMA DATA = B76.A;
IDENTIFY VAR = DIF_LOG_AIR STATIONARITY = (ADF);
RUN;
/*CHECK FOR SEASONALITY*/
PROC ARIMA DATA = B76.A;
IDENTIFY VAR = DIF_LOG_AIR NLAG = 60;
RUN;
DATA B76.A;
SET B76.A;
DIF12_DIF_LOG_AIR = DIF12(DIF_LOG_AIR);
RUN;
PROC ARIMA DATA = B76.A;
IDENTIFY VAR = DIF12_DIF_LOG_AIR NLAG = 60;
RUN;
/*CREATION OF DEVELOPMENT AND VALIDATION SAMPLE*/
DATA B76.D B76.V;
SET B76.A;
IF YEAR(DATE) = 1960 THEN OUTPUT B76.V;
ELSE OUTPUT B76.D;
RUN;
/*SELECTION OF P&Q*/
PROC ARIMA DATA = B76.D;
IDENTIFY VAR = DIF12_DIF_LOG_AIR MINIC;
RUN;
PROC ARIMA DATA = B76.D;
IDENTIFY VAR = DIF12_DIF_LOG_AIR;
ESTIMATE P = 1 Q = 1;
RUN;
PROC ARIMA DATA = B76.D;
IDENTIFY VAR = DIF12_DIF_LOG_AIR;
ESTIMATE P = 3 Q = 2;
RUN;
/*GENERATE FOR ALL COMBINATIONS*/
/*GENERATE THE FORECASTS*/
PROC ARIMA DATA = B76.D;
IDENTIFY VAR = DIF12_DIF_LOG_AIR;
ESTIMATE P = 2 Q = 3;
FORECAST LEAD = 12 ID = DATE 
INTERVAL = MONTH OUT = B76.F1;
RUN;
QUIT;
/*SHOULD USE THIS FORM*/
PROC ARIMA DATA = B76.D;
IDENTIFY VAR = LOG_AIR(1,12);
ESTIMATE P = 2 Q = 3;
FORECAST LEAD = 12 ID = DATE
INTERVAL = MONTH OUT = B76.F2;
RUN;
QUIT;
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\O.XLS";
PROC PRINT DATA = B76.V;
VAR DATE AIR;
RUN;
ODS HTML CLOSE;
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\F.XLS";
PROC PRINT DATA = B76.F2;
VAR FORECAST;
WHERE YEAR(DATE) = 1960;
RUN;
ODS HTML CLOSE;
/*USE THE BEST MODEL ON THE ENTIRE DATA*/
PROC ARIMA DATA = B76.A;
IDENTIFY VAR = LOG_AIR(1,12);
ESTIMATE P = 0 Q = 3;
FORECAST LEAD = 12 ID = DATE 
INTERVAL = MONTH OUT = B76.FN;
RUN;
QUIT;
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\F.XLS";
PROC PRINT DATA = B76.FN;
VAR FORECAST;
RUN;
ODS HTML CLOSE;
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 65\A.XLS";
PROC PRINT DATA = B76.A;
VAR DATE AIR;
RUN;
ODS HTML CLOSE;

