TREND - SMOOTH LONG TERM MOVEMENT W/O
MUCH FLUCTUATIONS
SEASONAL - PERIODIC MOVEMENTS PERIOD: 
<= 1 YEAR
CYCLICAL COMPONENT - PERIODIC MOVEMENTS 
PERIOD: >1 YEAR
IRREGULAR MOVEMENTS : RANDOM, ERRATIC
MOVEMENTS
/*ARIMA GROUP*/
1. VOLATILITY - SCATTER PLOT
VARIATION OF DATA INCREASES OR DECREASES 
OVER TIME - HIGHLY VOLATILE DATA
FAN SHAPED - SCALE DOWN (LOG/SQRT) 
OR INVERTED FAN - SCALE UP(EXP/SQUARE)
2. NON STATIONARY - RANDOM,MEMORY LESS
PROCESS WITHOUT ANY FIXED PATTERN
ADF TEST: H0: DATA IS NON STATIONARY
H1: DATA IS STATIONARY
P> ALPHA ACCEPT: H0 DATA IS NON STATIONARY
CAN BE MADE STATIONARY 
BY SUCCESSIVE DIFFERENCING;
DATA B73.A;
SET SASHELP.AIR;
LABEL AIR ="AIR";
RUN;
PROC GPLOT DATA = B73.A;
PLOT AIR*DATE;
RUN;
DATA B73.A;
SET B73.A;
LOG_AIR = LOG(AIR);
SQRT_AIR = AIR**0.5;
RUN;
PROC GPLOT DATA = B73.A;
PLOT SQRT_AIR*DATE;
RUN;
PROC GPLOT DATA = B73.A;
PLOT LOG_AIR*DATE;
RUN;
/*NON STATIONARITY CHECK*/
PROC ARIMA DATA = B73.A;
IDENTIFY VAR = LOG_AIR STATIONARITY = (ADF);
RUN;
DATA B73.A;
SET B73.A;
DIF_LOG_AIR = DIF(LOG_AIR);
RUN;
PROC ARIMA DATA = B73.A;
IDENTIFY VAR = DIF_LOG_AIR
STATIONARITY = (ADF);RUN;
/*SEASSONALITY*/
/*AUTO CORRELATION FUNCTION	(ACF)*/
/*ACF = CORR(Y(T),Y(T-S))						*/
/*IF ACF EXHIBITS HIGH VALUES AFTER */
/*FIXED INTERVAL WE CAN TAKE THE */
/*INTERVAL AS THE PERIOD OF SEASIONALITY.	*/
/*A DIFFERENCING OF THE SAME ORDER WITH */
/*DESEASONALIZE THE DATA.*/
PROC ARIMA DATA = B73.A;
IDENTIFY VAR = DIF_LOG_AIR NLAG = 60;RUN;
DATA B73.A;SET B73.A;
DIF12_DIF_LOG_AIR = DIF12(DIF_LOG_AIR);
RUN;
/*CREATION OF DEVELOPMENT AND VALIDATION SAMPLE*/
DATA B73.D B73.V;
SET B73.A;
IF YEAR(DATE) = 1960 THEN OUTPUT B73.V;
ELSE OUTPUT B73.D;
RUN;
